name: Test Self-Hosted Runner

on: [push, pull_request]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print System Info
        run: uname -a

      - name: List Files
        run: ls -alh
     name: Deploy with Docker

on:
  push:
    branches:
      - main  # Runs only when pushing to 'main' branch

jobs:
  deploy:
    runs-on: self-hosted  # This will run on your EC2 instance

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Stop and Remove Old Container (if running)
        run: |
          docker stop my-app-container || true
          docker rm my-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d --name my-app-container -p 3000:3000 my-app:latest
   
